const https = require('https');
const fs = require('fs-extra');
const os = require('os');
const path = require('path');
const unzipper = require('unzipper');
const { parseBindString } = require('../../../libs/helpers');

module.exports.init = async function init(hooks, app) {
    if (!app.conf.get('webserver.enabled') || !app.conf.get('webserver.public_dir')) {
        return;
    }
    let publicPath = app.conf.relativePath(app.conf.get('webserver.public_dir'));

    await downloadKiwiIrc(publicPath);

    // Get our listener port so that we can automatically put it into the kiwiirc config on the fly
    let port = 80;
    let binds = app.conf.get('listeners.bind', []);
    let bind = parseBindString(binds[0] || '');
    if (bind && bind.port) {
        port = parseInt(bind.port, 10);
    }

    app.webserver.router.get('kiwi.config', '/static/config.json', async (ctx, next) => {
        let config = await fs.readFile(path.join(publicPath, 'static', 'config.json'));
        config = JSON.parse(config);
        config = {
            ...config,
            '## comment': 'Auto generated by KiwiBNC',
            kiwiServer: '',
            startupScreen: 'welcome',
        };

        config.startupOptions = {
            ...config.startupOptions,
            port: port,
            server: '{{hostname}}',
            tls: false,
            direct: true,
            channel: '',
            bouncer: true,
            remember_buffers: false,
            public_register : app.conf.get('webchat.public_register', false),
        };

        // Add our kiwi plugin to the config
        config.plugins = config.plugins || [];
        config.plugins.push({
            name: 'kiwibnc',
            url: '/kiwibnc_plugin.html',
        });

        let extraConf = app.conf.get('webchat');
        for (let prop in extraConf) {
            config[prop] = extraConf[prop];
        }

        ctx.body = config;
    });

    app.webserver.router.post('kiwi.config', '/api/register', async (ctx, next) => {
        if (!app.conf.get('webchat.public_register', false)) {
            ctx.body = {error: 'forbidden'};
            return;
        }

        let body = ctx.request.body;
        if (!body.username || !body.email || !body.password) {
            ctx.body = {error: 'missing_params'};
            return;
        }

        if (await app.userDb.getUser(body.username)) {
            ctx.body = {error: 'username_in_use'};
            return;
        }

        try {
            let user = await app.userDb.addUser(body.username, body.password);
        } catch (err) {
            if (err.message === 'Invalid username') {
                ctx.body = {error: 'invalid_username'};
            } else {
                ctx.body = {error: 'unknown_error'};
            }

            return;
        }

        ctx.body = {error: false};
    });
};

async function downloadKiwiIrc(publicPath) {
    let downloadUrl = 'https://builds.kiwiirc.com/zips/kiwiirc_master.zip';
    let downloadPath = path.join(os.tmpdir(), 'kiwiirc_download');

    try {
        let dir = await fs.readdir(publicPath);
        if (dir.length > 0) {
            l.info('The public web folder is not empty, not downloading the KiwiIRC client.', publicPath);
            return;
        }
    } catch (err) {
        if (err.code !== 'ENOENT') {
            reportError(err);
            return;
        }
    }

    https.get(downloadUrl, async (response) => {
        if (response.statusCode !== 200) {
            reportError(new Error('Invalid response from the download server, ' + response.statusCode));
            return;
        }

        response
            .pipe(unzipper.Extract({path: downloadPath}))
            .on('error', reportError)
            .on('close', async () => {
                l.info('Downloaded. Copying to web folder...', publicPath);
                try {
                    await fs.copy(path.join(downloadPath, 'dist/'), publicPath);
                } catch (err) {
                    reportError(err);
                    return;
                }

                l.info('Kiwi IRC downloaded!');
            });
    })
    .on('error', reportError);

    function reportError(err) {
        l.error('Error downloading Kiwi IRC: ' + err.message);
    }
}
